alter table TESTTASK_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CONFILDES_ON_CONTRACT foreign key (CONTRACT_ID) references TESTTASK_CONTRACT(ID);
alter table TESTTASK_CONTRACT_FILE_DESCRIPTOR_LINK add constraint FK_CONFILDES_ON_FILE_DESCRIPTOR foreign key (FILE_DESCRIPTOR_ID) references SYS_FILE(ID);
