create table TESTTASK_SERVICE_COMPLETION_CERTIFICATE_FILE_DESCRIPTOR_LINK (
    SERVICE_COMPLETION_CERTIFICATE_ID uuid,
    FILE_DESCRIPTOR_ID uuid,
    primary key (SERVICE_COMPLETION_CERTIFICATE_ID, FILE_DESCRIPTOR_ID)
);
