alter table TESTTASK_CONTRACT add constraint FK_TESTTASK_CONTRACT_ON_STATUS foreign key (STATUS_ID) references TESTTASK_STATUS(ID);
create index IDX_TESTTASK_CONTRACT_ON_STATUS on TESTTASK_CONTRACT (STATUS_ID);
