alter table TESTTASK_STAGE add constraint FK_TESTTASK_STAGE_ON_CONTRACT foreign key (CONTRACT_ID) references TESTTASK_CONTRACT(ID);
create index IDX_TESTTASK_STAGE_ON_CONTRACT on TESTTASK_STAGE (CONTRACT_ID);
