-- begin TESTTASK_CONTRACT
alter table TESTTASK_CONTRACT add constraint FK_TESTTASK_CONTRACT_ON_CUSTOMER foreign key (CUSTOMER_ID) references TESTTASK_ORGANIZATION(ID)^
alter table TESTTASK_CONTRACT add constraint FK_TESTTASK_CONTRACT_ON_PERFORMER foreign key (PERFORMER_ID) references TESTTASK_ORGANIZATION(ID)^
create index IDX_TESTTASK_CONTRACT_ON_CUSTOMER on TESTTASK_CONTRACT (CUSTOMER_ID)^
create index IDX_TESTTASK_CONTRACT_ON_PERFORMER on TESTTASK_CONTRACT (PERFORMER_ID)^
-- end TESTTASK_CONTRACT
-- begin TESTTASK_STAGE
alter table TESTTASK_STAGE add constraint FK_TESTTASK_STAGE_ON_CONTRACT foreign key (CONTRACT_ID) references TESTTASK_CONTRACT(ID)^
create index IDX_TESTTASK_STAGE_ON_CONTRACT on TESTTASK_STAGE (CONTRACT_ID)^
-- end TESTTASK_STAGE
-- begin TESTTASK_SERVICE_COMPLETION_CERTIFICATE
alter table TESTTASK_SERVICE_COMPLETION_CERTIFICATE add constraint FK_TESTTASK_SERVICE_COMPLETION_CERTIFICATE_ON_STAGE foreign key (STAGE_ID) references TESTTASK_STAGE(ID)^
create index IDX_TESTTASK_SERVICE_COMPLETION_CERTIFICATE_ON_STAGE on TESTTASK_SERVICE_COMPLETION_CERTIFICATE (STAGE_ID)^
-- end TESTTASK_SERVICE_COMPLETION_CERTIFICATE
-- begin TESTTASK_INVOICE
alter table TESTTASK_INVOICE add constraint FK_TESTTASK_INVOICE_ON_STAGE foreign key (STAGE_ID) references TESTTASK_STAGE(ID)^
create index IDX_TESTTASK_INVOICE_ON_STAGE on TESTTASK_INVOICE (STAGE_ID)^
-- end TESTTASK_INVOICE
